Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    Domain: example.com

    # sovrals is the fully qualified domain of the peer.
    # replace example.com with your domain name
    CertificateAuthorities:
      - OrdererCA

    OrdererEndpoints:
      - orderer.example.com:7050

  - &Org1
    Name: Org1MSP
    Domain: org1.example.com

    # sovrals is the fully qualified domain of the orderer.
    # replace example.com with your domain name
    CertificateAuthorities:
      - Org1CA

    # Policies define the rules governing how this Org's identities
    # are used (e.g., what percentage must sign). This section is cryptic but
    # basically:
    #   Msps:
    #     Org1MSP:
    #       Policies:
    #         Readers:
    #           - 100% strength
    #         Writers:
    #           - 100% strength
    #         Admins:
    #           - 50% strength
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"

    AnchorPeers:
      # Prototype for other peers
      - Host: peer0.org1.example.com
        Port: 7051

  - &Org2
    Name: Org2MSP
    Domain: org2.example.com

    # sovrals is the fully qualified domain of the orderer.
    # replace example.com with your domain name
    CertificateAuthorities:
      - Org2CA

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"

    AnchorPeers:
      # Prototype for other peers
      - Host: peer0.org2.example.com
        Port: 7051

Orderer:
  OrdererType: etcdraft
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 983040
    PreferredMaxBytes: 512
  BatchTimeout: 2s
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  EtcdRaft:
    Consenters:
      - Host: orderer.example.com
        Port: 7050
        ClientTLSCert: orderer/exampleCA/ordererCert.cer
        ServerTLSCert: orderer/exampleCA/ordererCert.cer

Channel:
  Capacities:
    # constrain *
    Peer:
      Org1MSP: 20
      Org2MSP: 30

Application:
  <<: *Org1
  <<: *Org2
  Organizations:
    - *Org1
    - *Org2
