spring:
  application:
    name: Official
  datasource:
    url: jdbc:mysql://localhost:3306/autocrowd?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

server:
  port: 8080

jwt:
  secret: bbe0ac1a5b8a113b4568d55c76fe887a1cd99b01acfad7957156945688e03e20
  expiration: 86400000

# 区块链配置
fabric:
  mspId: Org1MSP
  channelName: mychannel
  orderChaincodeName: ordercontract
  financialChaincodeName: basic
  cryptoPath: ./blockchain/fabric-example/test-network/organizations/peerOrganizations/org1.example.com