spring:
  application:
    name: Official
  datasource:
    url: jdbc:mysql://localhost:3306/autocrowd?serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

server:
  port: 8080

jwt:
  secret: bbe0ac1a5b8a113b4568d55c76fe887a1cd99b01acfad7957156945688e03e20
  expiration: 86400000

# 区块链配置
fabric:
  mspId: Org1MSP
  channelName: mychannel
  orderChaincodeName: ordersLedger
  financialChaincodeName: financialsLedger
  cryptoPath: crypto-config/peerOrganizations/org1.example.com
#  certDirPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
#  keyDirPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  certDirPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts
  keyDirPath: crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore
  tlsCertPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peerEndpoint: localhost:7051
  peerHostAlias: peer0.org1.example.com